# Generated by Django 5.0.6 on 2024-06-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='Applicants',
        ),
    ]
