# Generated by Django 5.0.6 on 2024-06-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_applicant_applicants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Applicant',
        ),
    ]
