# Generated by Django 5.0.6 on 2024-07-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_applicants_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='last_name',
            new_name='position',
        ),
        migrations.AddField(
            model_name='applicant',
            name='message',
            field=models.TextField(default='Default Value'),
        ),
    ]
