# Generated by Django 5.0.6 on 2024-07-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_first_name_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='message',
            field=models.TextField(),
        ),
    ]
