# Generated by Django 5.0.6 on 2024-07-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_applicant_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='message',
            field=models.TextField(default='No Message'),
        ),
    ]
